{
 "title": "Mining Form Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Workers" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, Miners [Active] from vwMinerCountByTime where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select max(time) time, count(GPUIDX) Active from [dbo].[MinerGPUDetail] D inner join MinerSummary S on D.MinerSummaryID = S.ID \r\nwhere  \r\n $__timeFilter(time) \r\n and isnull(D.Performance,0) > 20\r\ngroup by D.RunID\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, ActualHashRate [Actual h/r] from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, AverageHashRate/1000000 [Pool h/r] from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, CoinsPerMin * 60 * 24 as [Coins/day]  from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, USDPerMin * 60 * 24 as [USD/day]  from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, ValidShares as [Valid Shares]  from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, isnull(InvalidShares,0) + isnull(StaleShares,0) as [Invalid Shares]  from EtherMineSummary where  $__timeFilter(time) "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, ETH from vwEthValue"
    }
   ]
  },
  {
   "title": "Miner1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner1'"
    }
   ]
  },
  {
   "title": "Miner2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner2'"
    }
   ]
  },
  {
   "title": "Miner3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner3'"
    }
   ]
  },
  {
   "title": "Miner4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner4'"
    }
   ]
  },
  {
   "title": "Miner5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner5'"
    }
   ]
  },
  {
   "title": "Miner6",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner6'"
    }
   ]
  },
  {
   "title": "Miner7",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select S.HashRate Miner1 from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner7'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner1'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower Outlet from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner1'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner2'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner2'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner3'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select isnull(S.SwitchPower, S.TotalPower) from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner3'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner4'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner4'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner5'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner5'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner6'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner6'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "GPUs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(GPUIDX) GPUs from [dbo].[MinerGPUDetail] D\r\ninner join MinerSummary S\r\non D.RunID = S.RunID\r\nand D.MinerSummaryID = S.ID\r\nwhere D.RunID in (select max(LastRunID) from Miners)\r\nand Miner = 'Miner7'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 23, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select S.SwitchPower from Miners M inner join MinerSummary S on M.LastRunID = S.RunID and M.Miner = S.Miner\r\nwhere M.LastRunID = (select max(LastRunID) from Miners) and M.Miner = 'Miner7'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where  Miner = 'Miner1'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where   Miner = 'Miner1'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where  Miner = 'Miner2'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where Miner = 'Miner2'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where Miner = 'Miner3'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where  Miner = 'Miner3'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where  Miner = 'Miner4'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where  Miner = 'Miner4'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where   Miner = 'Miner5'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where  Miner = 'Miner5'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where   Miner = 'Miner6'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where  Miner = 'Miner6'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 1, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Temp [ ] from vwMiningGPUs where  Miner = 'Miner7'"
    }
   ]
  },
  {
   "type": "bargauge",
   "description": "GPU Performance",
   "gridPos": { "h": 11, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select   'GPU ' + cast(GPUIDX as varchar(2)) as GPU, Performance as [ ] from vwMiningGPUs where  Miner = 'Miner7'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, USD from vwEthValue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select time, [x Rate] from vwEthValue"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner1",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner1'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner2",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner2'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner3",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner3'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner4",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner4'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner5",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner5'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner6",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner6'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "graph",
   "description": "Miner7",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n   time, \r\n   Miner , \r\n   HashRate as [Real], \r\n   ReportedHashRate as Reported,\r\n   CurrentHashRate as [Current]\r\nFROM \r\n   vwMinerSummary\r\nWHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner7'\r\nORDER BY 1 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select max(time) time, sum(isnull(SwitchPower, TotalPower)) Power from MinerSummary \r\nwhere  $__timeFilter(time) \r\ngroup by runid"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner1'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner2'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner3'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner4'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner5'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner6'"
    }
   ]
  },
  {
   "type": "stat",
   "description": "GPU Performance",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select  sum(case when SuccessFlag = 1 then 1 else 0 end) [Successful Restarts], sum(case when SuccessFlag = 0 then 1 else 0 end) [Failed Restarts]  from MinerRestarts WHERE \r\n   $__timeFilter(time) \r\n   and Miner = 'Miner7'"
    }
   ]
  }
 ]
}